name: Test transcriptions

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.12"
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install the project
        run: uv sync --locked --dev

      - name: Check format
        run: uv run ruff format --check

      - name: Check lint
        run: uv run ruff check

      - name: Check types
        run: uv run mypy momento_mori

      - name: Run tests
        run: uv run pytest
